### ISSUE TITLE
Support camelCase

### ISSUE THREAD

**Issue by ben-page** [MSNexploder/inflect#7]
Generally, the first letter is lower case in camel case naming. It would be nice to have a function that does this.

**Comment by ben-page** [comment]
I see that this is supported, but not documented.

**Comment by dylanfoster** [comment]
`camelize` is supported but it is incorrect `camelCase` is what I would expect it to return but it is returning `CameCase`

**Comment by MSNexploder** [comment]
`camelize` supports both `camelCase` and `CamelCase` - capitalizing the first letter being the default.

Actually this is documented:

```
# ### Examples
#     "active_record".camelize()              # => "ActiveRecord"
#     "active_record".camelize(false)         # => "activeRecord"
```

or without extensions:

```
# ### Examples
#     inflect.camelize("active_record")              # => "ActiveRecord"
#     inflect.camelize("active_record", false)       # => "activeRecord"
```

HTH
