### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by demian85** [MSNexploder/inflect#8]
What about Spanish? English is not the only language in the world, perhaps you should make a special mention about language support.
Thanks.

**Comment by MSNexploder** [comment]
Sorry, atm only english rules are included by default.

You can however add custom inflections rules:

```javascript
inflect.inflections(function(inflect) {
  inflect.plural(/(alias|status)$/i, '$1es');
  inflect.singular(/(n)ews$/i, '$1ews');
  // ...
});
```

HTH
