### ISSUE TITLE
Bug in Singularlize

### ISSUE THREAD

**Issue by thetutlage** [MSNexploder/inflect#9]
The singularize seems not be working fine with keywords like `Status`

Screen from runkit

<img width="1046" alt="screen shot 2016-11-13 at 1 17 50 pm" src="https://cloud.githubusercontent.com/assets/1706381/20244346/b200cdb8-a9a3-11e6-9d21-b62fe815bd39.png">

**Comment by tux-world** [comment]
is this bug resolved?

**Comment by MSNexploder** [comment]
this will be fixed in the soon to be released version 0.4.0
